---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: charts.rook.io-release
  namespace: kommander-flux
spec:
  interval: 10m
  timeout: 1m
  url: "https://charts.rook.io/release"
