---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nvidia-gpu-operator-1.11.1-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |-
    nfd:
      enabled: false
    driver:
      enabled: false
    toolkit:
      version: v1.10.0-centos7
    gfd:
      enabled: true
