apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: velero
  namespace: ${releaseNamespace}
spec:
  bucketName: velero
  storageClassName: dkp-store # Declared in rook-ceph-cluster : services/rook-ceph-cluster/1.10.1/defaults/cm.yaml
