---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: project-loki-object-bucket-claims
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: object-bucket-claim
      sourceRef:
        kind: HelmRepository
        name: takirala.github.io-charts-stable # TODO: delete this and uncomment next line
        # name: mesosphere.github.io-charts-stable
        namespace: kommander-flux
      version: 0.1.0
  interval: 15s
  install:
    crds: CreateReplace
    remediation:
      retries: 30
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 30
  releaseName: project-loki-object-bucket-claims
  valuesFrom:
    - kind: ConfigMap
      name: project-grafana-loki-0.48.5-d2iq-defaults
  targetNamespace: ${releaseNamespace}
