apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: project-loki-object-bucket-claims-helmrelease
  namespace: ${releaseNamespace}
spec:
  force: false
  prune: true
  wait: true
  interval: 6h
  retryInterval: 1m
  path: ./services/project-grafana-loki/0.48.5/objectbucketclaims
  sourceRef:
    kind: GitRepository
    name: management
    namespace: kommander-flux
  timeout: 1m
  postBuild:
    substitute:
      releaseNamespace: ${releaseNamespace}
