---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rook-ceph-cluster-1.10.1-d2iq-defaults
  namespace: ${releaseNamespace}
data:
  values.yaml: |
    ---
    operatorNamespace: ${releaseNamespace}
    clusterName: todo-cluster-loki-or-velero
    toolbox:
      # Enable a toolbox for debugging
      enabled: true # TODO(takirala): Disable toolbox by default

    # PSP is Unsupported in 1.25+ k8s
    # Set this to the same value as the rook-ceph chart.
    pspEnable: false
    
    # All values below are taken from the CephCluster CRD
    cephClusterSpec:
      cephVersion:
        image: quay.io/ceph/ceph:v17.2.3
      dataDirHostPath: /var/lib/rook

      mon:
        count: 3
        # Mons should only be allowed on the same node for test environments where data loss is acceptable.
        allowMultiplePerNode: false
        volumeClaimTemplate:
          spec:
            storageClassName:
            volumeMode: FileSystem
            resources:
              requests:
                storage: 10Gi

      mgr:
        count: 2
        allowMultiplePerNode: false

      dashboard:
        enabled: true
        urlPrefix: /ceph-dashboard
        port: 8444
        ssl: false

      storage:
        storageClassDeviceSets:
          - name: ceph-osd-set1
            count: 3
            portable: false
            encrypted: false
            volumeClaimTemplates:
              - metadata:
                  name: data
                spec:
                  resources:
                    requests:
                      storage: 10Gi
                  storageClassName:
                  # OSD Requires Block storage.
                  volumeMode: Block
                  accessModes:
                    - ReadWriteOnce
        onlyApplyOSDPlacement: false
        useAllDevices: false
        useAllNodes: false

    logLevel: DEBUG # TODO(takirala): INFO-fy after testing

    cephBlockPools: []
    cephFileSystems: []
    cephObjectStores:
      - name: dkp-store
        # see https://github.com/rook/rook/blob/master/Documentation/CRDs/Object-Storage/ceph-object-store-crd.md#object-store-settings for available configuration
        spec:
          metadataPool:
            replicated:
              size: 1
          dataPool:
            replicated:
              size: 1
          preservePoolsOnDelete: false
          gateway:
            port: 80
            # securePort: 443
            instances: 1
            priorityClassName: system-cluster-critical
          healthCheck:
            bucket:
              interval: 60s
        storageClass:
          enabled: true
          name: dkp-store # Defined once per namespace 

    monitoring:
      enabled: false # TODO(takirala): enable monitoring
      createPrometheusRules: false
